version: '3.7'

services:
    postgis:
        image: postgis/postgis:14-3.3
        environment:
            POSTGRES_PASSWORD: postgis
            POSTGRES_DB: postgis
            POSTGRES_USER: postgis
        ports:
            - 5435:5432    